feat(package): Add logreg package
fossology/Minerva-Dataset-Generation pull request #5
Opened 2022-06-28 11:08 UTC by its-sushant

## Description
This pr is to add model training code and the python package code for logistic regression model that has been created and published to [PyPi](https://pypi.org/project/logreg/0.1.0/)

## File Structure
                     .
                    └── logreg
                        ├── LICENSE
                        ├── MANIFEST.in
                        ├── README.md
                        ├── setup.py
                        └── src
                            ├── logreg
                            │   ├── data
                            │   │   └── logreg
                            │   └── __init__.py
                            └── model_train.py

## How to train
For training the model run `python path/to/model_train.py`

## Notes
Test for the implemented model is done locally by creating the agent for logisticRegression on [atarashi](https://github.com/fossology/atarashi) and the accuracy score that has been tested using [evaluator.py](https://github.com/fossology/atarashi/blob/master/atarashi/evaluator/evaluator.py) is **63%**

![Screenshot from 2022-06-23 19-03-59](https://user-images.githubusercontent.com/76658675/175316583-14515fd1-d833-49a8-930e-077420e420d3.png)

CC: @GMishx @Kaushl2208 @hastagAB @ag4ums @vasudevmaduri

2022-07-02 13:23 UTC, GMishx commented on Model-packages/logreg/src/model_train.py
> +            ("tfidf", TfidfTransformer()),
Just an idea came to my mind. Can we try using [BM25](https://en.wikipedia.org/wiki/Okapi_BM25) in place of TF-IDF and see if there are any improvements? This will also help us compare the two for the license domain.

2022-07-05 08:13 UTC, its-sushant commented on Model-packages/logreg/src/model_train.py
> +            ("tfidf", TfidfTransformer()),
Ya sure, I will try using [BM25](https://en.wikipedia.org/wiki/Okapi_BM25).

2022-07-05 08:15 UTC, its-sushant commented on Model-packages/logreg/src/model_train.py
> +            ("tfidf", TfidfTransformer()),
For now I have modified the code as suggested and also added the package for linear support vector machine model.

Thanks:)

2022-07-06 06:10 UTC, hastagAB commented on Model-packages/logreg/src/model_train.py
> +    for license_list in license_lists:
You can populate base_lists[] and license_texts[] in a single license_list loop. @its-sushant

2022-07-07 08:18 UTC, its-sushant commented on Model-packages/logreg/src/model_train.py
> +    for license_list in license_lists:
@hastagAB  thanks for noticing it, I will just make the changes.

2022-07-08 05:15 UTC, Kaushl2208 requested changes
Hey, I have found few uniformity issues, You can fix them up in no time :)

Cheers!!

2022-07-08 05:15 UTC, Kaushl2208 commented on Model-packages/linearsvc/src/model_train.py
> +    y_train = train_data.short_name
```suggestion
    Y_train = train_data.short_name
```

or lower caps the  X_train  as well :)

2022-07-08 05:15 UTC, Kaushl2208 commented on Model-packages/linearsvc/src/model_train.py
> +    logreg_model = logreg.fit(X_train, y_train)
Same here, The X_train and Y_train uniformity

2022-07-08 05:15 UTC, Kaushl2208 commented on Model-packages/logreg/src/model_train.py
> +    X_train = train_data.text
Same issue @its-sushant

2022-07-08 05:15 UTC, Kaushl2208 commented on Model-packages/logreg/src/model_train.py
> +    logreg_model = logreg.fit(X_train, y_train)
Here too :)

2022-07-08 05:15 UTC, Kaushl2208 commented on Model-packages/logreg/src/model_train.py
> +    print("Model training is started!")
```suggestion
    print("Model training has started!")
```

2022-07-08 08:10 UTC, its-sushant commented on Model-packages/logreg/src/model_train.py
> +    for license_list in license_lists:
Done with the suggested change

2022-07-08 08:10 UTC, its-sushant commented on Model-packages/linearsvc/src/model_train.py
> +    print("Model training is started!")
Done @Kaushl2208  bhaiya

2022-07-08 08:11 UTC, its-sushant commented on Model-packages/logreg/src/model_train.py
> +    X_train = train_data.text
Done

2022-07-08 08:11 UTC, its-sushant commented on Model-packages/logreg/src/model_train.py
> +    logreg_model = logreg.fit(X_train, y_train)
Done

2022-07-08 08:11 UTC, its-sushant commented on Model-packages/logreg/src/model_train.py
> +    print("Model training is started!")
Done

2022-07-18 08:18 UTC, Kaushl2208 approved these changes

2025-06-09 08:22 UTC, Kaushl2208 commented
Thank you for your contribution @its-sushant . However, the changes proposed in your PR might conflict with the primary responsibility of this repository, which is focused on DataSet Generation. Training the data and packaging should be managed within the Tool repository, such as Atarashi in our current setup. It's important to maintain separate repositories to address distinct responsibilities effectively.

Hence I would recommend to extend this training capability in Atarashi.


CC: @shaheemazmalmmd

2025-06-09 11:54 UTC, Kaushl2208 commented
Closing as discussed.

2025-06-09 11:54 UTC, closed without merging